### ISSUE TITLE
Whisper speaker diarization returns NaN for timestamps

### ISSUE THREAD

**Issue by patrick-ve** [huggingface/transformers.js#1077]
### System Info

```
Node.js v20.10.0
@huggingface/transformers v3.1.0
Chrome 131
```

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I have cloned the example [repo](https://huggingface.co/spaces/Xenova/whisper-speaker-diarization/tree/main/whisper-speaker-diarization) and made some changes to the `transformers` dependencies, as I immediately got an error upon installing dependencies.

I have replaced "@xenova/transformers": `"github:xenova/transformers.js#v3"` with `"@huggingface/transformers": "^3.1.0"`. Also replaced the import in `worker.js`.

After loading the model and attempting to transcribe the example video, a table gets logged, where each `start` and `end` segment is `NaN`. 

![Screenshot 2024-12-07 at 20 06 55](https://github.com/user-attachments/assets/7b174c8c-0576-4561-a696-fbc962298a73)

### Reproduction

Clone my repository, install dependencies and run the dev server. Use the following steps:

```
git clone https://github.com/patrick-ve/speaker-diarization-example
yarn install
yarn dev
```

**Comment by patrick-ve** [comment]
I managed to figure out that property `post_process_speaker_diarization` does not exist on type `Processor`, which causes NaN to appear as start/end values.

Follow up question: where would `post_process_speaker_diarization` be imported from?

**Comment by xenova** [comment]
Thanks for debugging! I've identified the problem, which https://github.com/huggingface/transformers.js/pull/1082 will fix.

I'll also open a follow-up PR to improve the unit tests for the model.

**Comment by patrick-ve** [comment]
Thanks for your quick reply. A quick workaround I discovered earlier would be to downgrade to `@huggingface/transformers: "3.0.0"`.

I have another small question that is related to this model. How would one track progress of the actual speaker diarization progress? The example code provided mentions a `progress_callback` property, but this handles tracking progress of loading the models:

```js
    this.segmentation_processor ??= AutoProcessor.from_pretrained(
      this.segmentation_model_id,
      {
        progress_callback,
      }
    );
```

I thought that adding a `callback_function` property to the `transcribe` instance would be enough, but this doesn't seem to work with a `AutoModelForAudioFrameClassification` model. I'm looking for something similar to this other [transcribing example](https://huggingface.co/spaces/Xenova/whisper-web).

**Comment by xenova** [comment]
Closed in https://github.com/huggingface/transformers.js/commit/14bf689c983c68c7e870b970e1bcce79c791c3c9 👍 

To respond to your question on progress: The model processes the audio all at once, and the post processing acts on the model output, so while there's technically no way to do it within the modelling code, you should be able to do something similar as follows:
1. Split the audio into 10 second chunks (potentially overlapping). This is actually what the model was [designed for](https://huggingface.co/pyannote/segmentation-3.0#:~:text=This%20model%20ingests%2010%20seconds%20of%20mono%20audio%20sampled)
2. Process the chunks separately. This is where you can track progress .
3. Post-process all the chunks and merge.

Note that you would need to employ some form of speaker identification model into the pipeline to ensure that the same speaker is assigned across chunks (since there won't be any consistency across chunks)

**Comment by patrick-ve** [comment]
Thanks for the insight, it is much appreciated! I have decided to reduce complexity by not implementing speaker identification.

As of now, I process the first 10 seconds of the audio, which returns the elapsed time. I then multiply this number by the amount of chunks to get a very rough estimated time to completion. I then show a loading bar that progresses over this estimated time. This should be enough as an enhanced user experience.
