### ISSUE TITLE
[Feature request] Update ONNX runtime to version 1.15.1

### ISSUE THREAD

**Issue by ocavue** [huggingface/transformers.js#298]
**Name of the feature**
 
Currently, the latest transformers.js is dependent on onnxruntime-web v1.14.0. Since onnxruntime-web [v1.15.1](https://github.com/microsoft/onnxruntime/releases/tag/v1.15.1) has been released for months, I'd love to see if it's possible to update this dependency version. 

**Reason for request**
 

ONNX runtime has added a preview support for WebGPU in version 1.15.0. I'd love to try it with transfomers.js. I understand that there may be additional work required for WebGPU support, but updating the ONNX runtime version could be a good starting point I guess. Really appreciate your work here.

**Additional context**

N/A

**Comment by xenova** [comment]
Hi there 👋 The main reason we haven't yet updated to 1.15 (or above) is because the WebGPU support at that stage was very incomplete and was not available as a simple "execution provider".

Now, the support for it is nearing completion, and quite a few encoder-only models work quite well with it! However, for models with decoders, there is a performance bottleneck which is a result of a lack of IO-binding. See [here](https://github.com/microsoft/onnxruntime/issues/17373).

Sere [here](https://github.com/microsoft/onnxruntime/pulls?q=js%2Fweb) to keep updated with the progress,

**Comment by dakenf** [comment]
I think the next release will be huge since it also includes GPU support for node. And i'll add LLM support to Attention operator. It does not only increase speed but also reduced VRAM usage for StableDiffusion from 10gb to ~5.6 with fp32 model
Also, fp16 support is almost done, so stay tuned
