### ISSUE TITLE
How do I use WebGL as executionProvider?

### ISSUE THREAD

**Issue by kwaroran** [huggingface/transformers.js#505]
### Question

```js
export const executionProviders = [
    // 'webgpu',
    'wasm'
];
```
I looked at src/backends/onnx.js and noticed that there was no webgl in the executionProviders.
Is there a way to use WebGL as executionProvider?

**Comment by xenova** [comment]
I disabled the WebGL EP because I couldn't reliably get the set of transformers.js models working with it... and seeing that WebGPU is its successor (which ORT is actively working on), I don't expect the WebGL EP to be well supported in future.

That said, if you would like to try with it, feel free to fork the library, add the webgl execution provider, and build the library yourself. If you do, let me know what models you try to run (and if they work) 😇
