### ISSUE TITLE
Supporting Multiple Pipelines?

### ISSUE THREAD

**Issue by kelayamatoz** [huggingface/transformers.js#975]
### Question

First of all, thank you so much for creating transformers.js! This is a fantastic library, and I had lots of fun building with it!

I have a question regarding using pipelines API: Would it be possible to start multiple pipelines? For example, instead of using just one pipeline to run inference, can we create a pool of pipelines and push jobs into this pool, potentially better utilize the multi-cores on modern laptops? 

The goal here is really to understand if there's ways to utilize multi-cores. No worries if not! I just want to understand where the limits are.

Thanks!

**Comment by flatsiedatsie** [comment]
I do this by running pipelines in multiple web-workers. In general I'd say that running the pipelines inside web-workers is a good idea.

> potentially better utilize the multi-cores on modern laptops?

Possibly, if you have a huge amount of cores. Transformers.js will aready use multiple cores (as long as your webpage has been cross-origin-isolated). But there is a limit to how much adding another core will improve speed, so running two pipelines in parallel might be useful in that case, if your task can be parallelized.

Keep in mind: 
- The biggest bottleneck with LLM's is usually the speed of your memory.
- If at all possible you should use Transformers.js V3, which has GPU support. It runs things MUCH faster (hint: because your GPU has much faster memory).
